spring:
  profiles:
    default: local

  output:
    ansi:
      enabled: always

  # SMTP
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_ID}
    password: ${SMTP_PW}
    properties:
      debug: true
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true

# Spring Security
jwt:
  claim: ${CLAIM}
  secret: ${JWT_SECRET_KEY}
  token-validity-in-seconds: ${JWT_VALID_TIME}

cloud:
  aws:
    region:
      static: us-east-1
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
