openapi: 3.0.3
info:
  title: Web IDE
  description: Web IDE
  version: 1.0.1
servers:
  - url: 'http://localhost:8080/api'
paths:
  /v1/auth/signin:
    $ref: './auth/signin.yaml'
  /v1/auth/signup:
    $ref: './auth/signup.yaml'
  /v1/projects:
    $ref: './project/create.yaml'
  /v1/projects/{id}:
    $ref: './project/update.yaml'
  /v1/projects/{id}/run:
    $ref: './project/run.yaml'
  /v1/projects/{id}/invite:
    $ref: './project/invite.yaml'
  /v1/projects/{projectId}/files/{fileId}:
    $ref: './project/save.yaml'

components:
  schemas:
    Node:
      type: object
      properties:
        id:
          type: number
          description: 파일 및 폴더 식별자
        key:
          type: number
          description: 파일 및 폴더 계층 구조
          example: "0-1"
        title:
          type: string
          description: 파일 및 폴더 제목
        type:
          type: string
          description: 파일 및 폴더 구분자
          enum: [folder, file]
        content:
          type: string
          description: 파일 내용
        children:
          type: array
          description: 하위 파일 및 폴더 정보
          items:
            $ref: '#/components/schemas/Node'

    FileAndFolderStructure:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Node'


